apiVersion: v1
kind: Service

metadata:
  name: fast-hello-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: fast-hello
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: fast-hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-hello
  template:
    metadata:
      labels:
        app: fast-hello
    spec:
      containers:
      - name: fastapi
        image: docker.io/hanubindh/fast_hello:latest
        ports:
        - containerPort: 80