apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort # Use NodePort for Play with K8s, LoadBalancer for cloud providers with LB support
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 # Only specify nodePort if using NodePort type
  selector:
    app: hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: hanubindh/fast_hello
          ports:
            - containerPort: 80
